id: A394A1313
title: 'The Gathering of Blessings: A Guru Yoga'
type: translation
pechas:
- IC4C7AC4B
- IBB3B8EB3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:13:27.308009
  last_modified_at: 2023-01-04 12:13:27.308024
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IC4C7AC4B/7380: 3A03
  IBB3B8EB3/7D0D: 3A03
